### PR TITLE
#20 Added Download Now Button

### PR DESCRIPTION
**Pull request by boomboss200**
Replaced Buy Now button with Download now that downloads the content in jpg format
Screenshot 2023-02-05 at 4 21 32 PM

### CODE REVIEW

**Comment by Nababratadeb-NITA** [comment]
hey @boomboss200 can you please recheck my repo i am facing some issue with my code

**Comment by boomboss200** [comment]
What kind of issue ? Sent from my iPhoneOn 06-Feb-2023, at 11:35 AM, Nababrata Deb ***@***.***> wrote:﻿
hey @boomboss200 can you please recheck my repo i am facing some issue with my code

**Comment by boomboss200** [comment]
@Nababratadeb-NITA do let me know the issue that you are having also would be great if you can provide the screenshot as well

**Comment by Nababratadeb-NITA** [comment]
Hey @boomboss200  when I download the image it shows that it's not supported or file may be corrupted can you fix the issue

**Comment by boomboss200** [comment]
okay. I will check on that later, if I can find any fix to it.  isn't the downloaded file in the jpg format ?

**Comment by boomboss200** [comment]
@Nababratadeb-NITA how do the users get the product when they buy after the going through the cart process. 
i.e
how do they recieve these products after paying and buying them..

**Comment by Nababratadeb-NITA** [comment]
> @Nababratadeb-NITA how do the users get the product when they buy after the going through the cart process. 
> i.e
> how do they recieve these products after paying and buying them..

Through the mail

**Comment by boomboss200** [comment]
that mail contains the same file as the user gets through the download button

**Pull request merged**
